name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short commit hash
        id: sha
        run: |
          echo "sha=$(git rev-parse --short=7 HEAD)" >> $GITHUB_OUTPUT

      - name: Get current date (YYMMDD)
        id: date
        run: |
          echo "date=$(date +'%y%m%d')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/tools:v${{ steps.date.outputs.date }}-${{ steps.sha.outputs.sha }}
            ghcr.io/${{ github.repository_owner }}/tools:latest